[package]
name = "dicom-gr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
chrono = "0.4.45"
dicom-core = "0.10.0"
dicom-dictionary-std = "0.10.0"
dicom-object = "0.10.0"
dicom-transfer-syntax-registry = "0.10.0"
dicom-ul = { "version" = "0.10.0", features = ["async"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
embed-resource = "3.0.11"
