use dicom_dictionary_std::uids;

pub const C_ECHO_RQ: u16 = 0x0030;
pub const C_ECHO_RSP: u16 = 0x8030;

pub const C_STORE_RQ: u16 = 0x0001;
pub const C_STORE_RSP: u16 = 0x8001;

pub const C_FIND_RQ: u16 = 0x0020;
pub const C_FIND_RSP: u16 = 0x8020;

pub const TRANSFER_SYNTAXES: &[&str] = &[
    uids::EXPLICIT_VR_LITTLE_ENDIAN,
    uids::IMPLICIT_VR_LITTLE_ENDIAN,
];

pub const ABSTRACT_SYNTAX: &[&str] = &[
    uids::VERIFICATION,
    uids::CT_IMAGE_STORAGE,
    uids::OPHTHALMIC_PHOTOGRAPHY8_BIT_IMAGE_STORAGE,
    uids::OPHTHALMIC_PHOTOGRAPHY16_BIT_IMAGE_STORAGE,
    uids::SECONDARY_CAPTURE_IMAGE_STORAGE,
    uids::OPHTHALMIC_TOMOGRAPHY_IMAGE_STORAGE,
    uids::OPHTHALMIC_OPTICAL_COHERENCE_TOMOGRAPHY_EN_FACE_IMAGE_STORAGE,
    uids::OPHTHALMIC_OPTICAL_COHERENCE_TOMOGRAPHY_BSCAN_VOLUME_ANALYSIS_STORAGE,
    uids::MODALITY_WORKLIST_INFORMATION_MODEL_FIND,
];
